name: ParoissienController
form: $/saintmathieu/paroisse/models/paroissienmodel/fields.yaml
modelClass: saintmathieu\Paroisse\Models\ParoissienModel
defaultRedirect: saintmathieu/paroisse/paroissiencontroller
create:
    redirect: 'saintmathieu/paroisse/paroissiencontroller/update/:id'
    redirectClose: saintmathieu/paroisse/paroissiencontroller
update:
    redirect: saintmathieu/paroisse/paroissiencontroller
    redirectClose: saintmathieu/paroisse/paroissiencontroller
