name: TestControler
modelClass: saintmathieu\Parametrage\Models\ProfessionModel
form: $/saintmathieu/parametrage/models/professionmodel/fields.yaml
defaultRedirect: saintmathieu/parametrage/testcontroler
create:
    redirect: 'saintmathieu/parametrage/testcontroler/update/:id'
    redirectClose: saintmathieu/parametrage/testcontroler
update:
    redirect: saintmathieu/parametrage/testcontroler
    redirectClose: saintmathieu/parametrage/testcontroler
preview: {  }
