name: ActiviteController
form: $/saintmathieu/paroisse/models/activitemodel/fields.yaml
modelClass: saintmathieu\Paroisse\Models\ActiviteModel
defaultRedirect: saintmathieu/paroisse/activitecontroller
create:
    redirect: 'saintmathieu/paroisse/activitecontroller/update/:id'
    redirectClose: saintmathieu/paroisse/activitecontroller
update:
    redirect: saintmathieu/paroisse/activitecontroller
    redirectClose: saintmathieu/paroisse/activitecontroller
