list: $/saintmathieu/parametrage/models/professionmodel/columns.yaml
modelClass: saintmathieu\Parametrage\Models\ProfessionModel
title: ProfessionModel
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'saintmathieu/parametrage/professionmodel/update/:id'
