list: $/saintmathieu/paroisse/models/eglisemouvement/columns.yaml
modelClass: saintmathieu\Paroisse\Models\EgliseMouvement
title: EgliseMouvementController
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'saintmathieu/paroisse/eglisemouvementcontroller/update/:id'
